language: "en-US"
early_access: true
reviews:
  review_status: true
  profile: "assertive"
  request_changes_workflow: false
  high_level_summary: true
  poem: true
  collapse_walkthrough: false
  auto_review:
    enabled: true
    ignore_title_keywords:
      - "WIP"
      - "DO NOT MERGE"
    drafts: false
chat:
  auto_reply: true
