contact_links:
  - name: Feature request
    url: https://github.com/moclojer/moclojer/discussions/new?category=ideas
    about: Suggest an idea for moclojer
  - name: Questions & Help
    url: https://github.com/moclojer/moclojer/discussions/new?category=q-a
    about: Ask a question about moclojer
  - name: Feedback
    url: https://github.com/moclojer/moclojer/discussions/categories/show-and-tell
    about: Discuss where moclojer can be improved
