on:
  push:
    branches:
      - "graal-build"
jobs:
  build:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/cache@v2"
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: "${{ runner.os }}-maven-${{ hashFiles('deps.edn') }}"
      - uses: "graalvm/setup-graalvm@v1"
        with:
          version: "22.0.0.2"
          java-version: "17"
          components: "native-image"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - uses: "DeLaGuardo/setup-clojure@4.0"
        with:
          cli: "1.10.3.1075"
      - name: "Download deps"
        run: |
          clojure -P
          clojure -A:dev -P
      - run: "clojure -A:dev -M --report stderr -m moclojer.build"
      - uses: "actions/upload-artifact@v2"
        with:
          name: native-dist
          path: |
            moclojer
