name: Build jar

on: [pull_request, workflow_call]

jobs:
  build-jar:
    runs-on: "ubuntu-20.04"
    steps:
    - uses: "actions/checkout@v4"
    - uses: "actions/cache@v3.3.2"
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
        key: "${{ runner.os }}-deps-${{ hashFiles('deps.edn') }}"
    - uses: "DeLaGuardo/setup-clojure@12.1"
      with:
        cli: "1.11.1.1139"
        github-token: "${{ secrets.GITHUB_TOKEN }}"
    - run: "clojure -M:dev --report stderr -m moclojer.build"
      env:
        CI_COMMIT_SHA: "${{ github.sha }}"
    # save target folder at artifact
    - uses: "actions/upload-artifact@v3.1.3"
      with:
        name: moclojer_target
        path: target
    # save .jar as artifact, used in release
    - uses: "actions/upload-artifact@v3.1.3"
      with:
        name: moclojer_jar
        path: target/moclojer.jar
