name: docker

on: [push, workflow_call]

permissions:
  contents: write

jobs:
  release:
    runs-on: "ubuntu-20.04"
    environment: release
    steps:
    - uses: actions/checkout@v3
    - name: docker build
      run: docker build -t ghcr.io/moclojer/moclojer:dev .
    - name: ghcr.io login
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.RELEASE_TOKEN }}

    - name: ghcr.io push moclojer:dev @ branch main
      if: github.ref_name == 'main'
      run: |
        docker build -t ghcr.io/moclojer/moclojer:dev .
        docker push ghcr.io/moclojer/moclojer:dev

    - name: ghcr.io push moclojer:latest @ tag v*
      if: startsWith(github.event.ref, 'refs/tags/v')
      run: |
        docker build -t ghcr.io/moclojer/moclojer:latest .
        docker tag ghcr.io/moclojer/moclojer:latest ghcr.io/moclojer/moclojer:${{ env.RELEASE_NAME }}
        docker push ghcr.io/moclojer/moclojer:latest
        docker push ghcr.io/moclojer/moclojer:${{ env.RELEASE_NAME }}
