name: linter

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: '1.11.3'
      - uses: clojure-lsp/setup-clojure-lsp@test-action
        with:
          clojure-lsp-version: 2024.04.22-11.50.26
      - name: clojure-lsp
        run: |
          clojure-lsp clean-ns --dry && \
          clojure-lsp format --dry
 
