name: linter

on: [push, pull_request]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: DeLaGuardo/setup-clj-kondo@v1
        with:
          version: '2022.05.31'
      - uses: actions/checkout@v3.0.2
      - name: clj-kondo
        run: clj-kondo --lint src test
