name: Tests
on: [push, pull_request]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          submodules: true
      - uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: "21.0.0.java11"
      - uses: DeLaGuardo/setup-clojure@4.0
        with:
          cli: "1.10.2"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: clojure -M:test
