name: tests
on:
  push:
  pull_request:
  workflow_run:
    workflows: ["linter"]
    types:
      - completed
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: DeLaGuardo/setup-clojure@7.0
        with:
          cli: "1.11.1.1139"
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: clojure -M:test
